# This is a basic workflow to help you get started with Actions

name: Deploy to github-pages

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Trigger after completion of either Fetch Contests or Fetch Blacklisted Contests action
  workflow_run:
    workflows: ["Fetch Latest Contests", "Fetch Blacklisted Contests"]
    types: [ completed ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Run current action only if previous actions have completed successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup node 14
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
      - name: Build and Publish
        run: |
            npm ci
            npm run build
            cd dist
            echo "cf-tracker.tech" > CNAME
            git config --global user.email "anuragcarbon1998@gmail.com"
            git config --global user.name "geekypandey"
            git init .
            git add -A
            git commit -m 'new build'
            git push -f https://geekypandey:${{secrets.GITHUB_TOKEN}}@github.com/geekypandey/cf_tracker.git master:gh-pages

