# This is a basic workflow to help you get started with Actions

name: Fetch Latest Contests

# Controls when the action will run.
on:
  schedule:
    - cron: '30 9,17,23 * * *'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      working-directory: ./scripts

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
        working-directory: ${{env.working-directory}}
      - name: Run script
        run: |
          if ./get_new_contests.sh; then
            git config --global user.email "anuragcarbon1998@gmail.com"
            git config --global user.name "geekypandey"
            git add -A
            git commit -m 'update contests.json'
            git push
          else
            exit 1
          fi
        working-directory: ${{env.working-directory}}


